### PR TITLE
Streaming transformation!

### PR DESCRIPTION
**Pull request by TehShrike**
- added a test with a larger file that most likely will be chunked in a stream
- transformation is now streaming using through2

### CODE REVIEW

**Comment by saibotsivad** [comment]
Ooh, nice!

One thing I'm worried about with this is to make sure that a base64 stream is chunked correctly.

In other words, there shouldn't be any padding added between chunks, only padded at the end.

Because I was just concatenating the streams I want worried about it, but handling chunks I'd want a test to make sure base64 passing was correct.

On December 12, 2015 1:06:17 PM CST, Josh Duff notifications@github.com wrote:

> - added a test with a larger file that most likely will be chunked in a
>   stream
> - transformation is now streaming using through2
>   You can view, comment on, or merge this pull request online at:
>   
>   https://github.com/tobiaslabs/pipe-transform-cli/pull/1
> 
> -- Commit Summary --
> - Streaming transformation!
> 
> -- File Changes --
> 
>    A .npmignore (2)
>    M bin.js (50)
>    M package.json (5)
>    A test-image-datauri-output.txt (1)
>    A test-image.jpg (0)
>    M test.js (29)
> 
> -- Patch Links --
> 
> https://github.com/tobiaslabs/pipe-transform-cli/pull/1.patch
> https://github.com/tobiaslabs/pipe-transform-cli/pull/1.diff
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/tobiaslabs/pipe-transform-cli/pull/1

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by TehShrike** [comment]
You mean like the base64url test that I added, but with the plain base64 encoding?

**Comment by saibotsivad** [comment]
Oh, I see it. I'm on my phone so I didn't see the test. I'll check it and merge it when I get home.

Thanks!

On December 12, 2015 7:09:05 PM CST, Josh Duff notifications@github.com wrote:

> You mean like the base64url test that I added, but with the plain
> base64 encoding?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/tobiaslabs/pipe-transform-cli/pull/1#issuecomment-164207860

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by TehShrike** [comment]
I added that test and made sure it was passing before I implemented streaming.

**Comment by saibotsivad** [comment]
Oh man, I should not try to review pull requests from my phone!

I just looked this over, and it looks great! Thanks for this! :clap:

**Pull request merged**
